apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: webapp-secret
spec:
  encryptedData:
    DB_PASSWORD: AgDummyEncryptedValue
    API_KEY: AgDummyEncryptedValue
  template:
    metadata:
      name: webapp-secret
